import { ObjectId } from "mongodb";
import { getServerSession } from "next-auth";
import { NextResponse } from "next/server";
import { z } from "zod";
import { FREE_SIGNUP_CREDITS, reserveGenerationCredit, refundGenerationCredit, type UserAccount } from "../../../lib/account";
import { authOptions } from "../../../lib/auth";
import clientPromise from "../../../lib/mongodb";

const requestSchema = z.object({
  figmaLink: z.string().trim().optional(),
  prompt: z.string().trim().min(3, "Describe what you want to build."),
  referenceImage: z
    .object({
      data: z.string().min(1),
      mimeType: z.string().min(1),
      name: z.string().min(1),
    })
    .optional(),
  currentGeneration: z
    .object({
      id: z.string().optional(),
      title: z.string().optional(),
      summary: z.string().optional(),
      prompt: z.string().optional(),
      previewHtml: z.string().optional(),
      previewCss: z.string().optional(),
      previewJs: z.string().optional(),
      files: z
        .array(
          z.object({
            path: z.string().min(1),
            content: z.string(),
          }),
        )
        .optional(),
    })
    .optional(),
});

const generationSchema = z.object({
  title: z.string().min(1),
  summary: z.string().min(1),
  previewHtml: z.string().min(1),
  previewCss: z.string().min(1),
  previewJs: z.string().optional().default(""),
  files: z
    .array(
      z.object({
        path: z.string().min(1),
        content: z.string(),
      }),
    )
    .min(1),
  notes: z.array(z.string()).optional().default([]),
});

const fileChangeSchema = z.object({
  path: z.string().min(1),
  action: z.enum(["created", "edited"]),
});

const WEBSITE_GENERATION_SYSTEM_PROMPT = `SYSTEM PROMPT:
You are an expert senior frontend engineer and product designer. You build beautiful, polished, production-ready React + Tailwind websites. Your output should look like something generated by v0, Lovable, Framer, or a high-end design agency.

For every user request:
- First understand the exact type of website/app requested.
- Choose a strong visual direction.
- Create a design system with colors, typography, spacing, cards, buttons, and layout rules.
- Generate a complete responsive website.
- Use realistic content.
- Use modern Tailwind styling.
- Use icons where useful using CSS, text symbols, or inline-safe shapes; do not import icon packages unless already included.
- Use gradients, glassmorphism, soft shadows, hover states, transitions, and micro-interactions where appropriate.
- Make the UI feel complete and premium.
- Make every section useful and visually intentional.

QUALITY BAR:
The output must not look like a beginner project. It should look like a polished portfolio/demo-worthy product.

Internal design checklist before returning:
- Is the page visually premium?
- Is spacing consistent?
- Is typography modern?
- Are sections complete?
- Are cards populated with real content?
- Are buttons styled properly?
- Is the layout responsive?
- Does the result match the user prompt?
- Does it look better than a basic HTML mockup?

Never generate plain white pages with random boxes, empty cards, unstyled navbars, misaligned sections, placeholder-only text, huge blank spaces, unfinished sections, or single-color rectangles pretending to be components.`;

const PREMIUM_OUTPUT_REQUIREMENTS = `PREMIUM OUTPUT REQUIREMENTS:
- Generate a finished product experience, not a sketch, wireframe, starter screen, or tutorial mockup.
- The first viewport must look impressive immediately and fill the available preview area.
- Use a real visual system: deliberate background, surfaces, borders, shadows, accent color, type scale, spacing rhythm, and hover states.
- Use domain-specific content. Never use generic labels like "Video Title", "Product Name", "Card title", "Feature one", or lorem ipsum.
- Include enough repeated realistic items to feel real: feeds need many posts, video apps need many video cards, stores need many products, dashboards need many metrics/rows, landing pages need complete sections.
- Avoid tiny demos with one card, one section, one centered panel, or lots of empty whitespace.
- Preview markup must be rich enough to judge the result without running React.
- React output and preview output must visually match.
- Prefer tasteful density over sparse emptiness. Use layered sections, split layouts, sidebars, tabs, chips, tables, cards, mockups, and data where appropriate.
- Use responsive layouts that meaningfully change on mobile instead of just shrinking desktop.
- Keep code clean, but prioritize visual completeness and prompt accuracy.`;

const geminiFallbackModels = ["gemini-3.5-flash", "gemini-2.5-flash", "gemini-2.0-flash", "gemini-1.5-flash"];
const maxAiAttemptsPerModel = 1;
const aiRequestTimeoutMs = 120000;

type AiProvider = "gemini" | "openrouter";
type WebsiteType =
  | "saas-landing"
  | "ai-tool-landing"
  | "fashion-ecommerce"
  | "restaurant-cafe"
  | "portfolio"
  | "agency"
  | "video-platform-dashboard"
  | "social-feed"
  | "marketplace"
  | "fintech-landing"
  | "mobile-app-landing"
  | "admin-dashboard"
  | "generic";

type PromptAnalysis = {
  websiteType: WebsiteType;
  visualStyle: string[];
  requiredSections: string[];
  brandName: string;
  targetAudience: string;
  cloneIntent: string;
};


type GeminiResponse = {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
      }>;
    };
  }>;
  error?: {
    message?: string;
  };
};

type OpenRouterResponse = {
  choices?: Array<{
    message?: {
      content?: string | Array<{ type?: string; text?: string }>;
    };
  }>;
  error?: {
    message?: string;
  };
};

export async function POST(request: Request) {
  const session = await getServerSession(authOptions);

  if (!session?.user) {
    return NextResponse.json({ error: "You must be signed in to generate." }, { status: 401 });
  }

  const provider = getAiProvider();
  const apiKey = provider === "openrouter" ? process.env.OPENROUTER_API_KEY : process.env.GEMINI_API_KEY;

  const body = await request.json().catch(() => null);
  const parsed = requestSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json({ error: parsed.error.issues[0]?.message ?? "Invalid request." }, { status: 400 });
  }

  const client = await clientPromise;
  const db = client.db();
  const users = db.collection<UserAccount>("users");
  const creditReservation = await reserveGenerationCredit(users, session.user);

  if (!creditReservation) {
    return NextResponse.json({ error: "Account not found." }, { status: 404 });
  }

  if (!creditReservation.ok) {
    return NextResponse.json(
      { error: "You are out of credits. Buy a plan to keep generating.", creditsRemaining: creditReservation.credits, creditLimit: FREE_SIGNUP_CREDITS },
      { status: 402 },
    );
  }

  try {
    let result: z.infer<typeof generationSchema>;

    if (!apiKey) {
      console.warn(`[Mosaic generation] ${provider} API key is not configured; using local reliable generation.`);
      result = createReliableGeneration(parsed.data.prompt, "AI provider key missing");
    } else {
      try {
        result = enforceGenerationQuality(
          parsed.data.prompt,
          await generateWithAi({
            provider,
            apiKey,
            figmaLink: parsed.data.figmaLink,
            prompt: parsed.data.prompt,
            referenceImage: parsed.data.referenceImage,
            currentGeneration: parsed.data.currentGeneration,
          }),
        );

        const qualityIssues = validateGeneratedQuality(parsed.data.prompt, result);

        if (qualityIssues.length) {
          console.warn(`[Mosaic generation] generated UI quality warnings: ${qualityIssues.join("; ")}; using local reliable generation.`);
          result = createReliableGeneration(parsed.data.prompt, qualityIssues.join("; "));
        }
      } catch (error) {
        console.warn(`[Mosaic generation] AI provider failed; using local reliable generation: ${error instanceof Error ? error.message : "Unknown error."}`);
        result = createReliableGeneration(parsed.data.prompt, error instanceof Error ? error.message : "AI provider failed");
      }
    }

    const now = new Date();
    const generationRecord = {
      ...result,
      prompt: parsed.data.prompt,
      figmaLink: parsed.data.figmaLink,
      referenceImageName: parsed.data.referenceImage?.name,
      userId: creditReservation.userId,
      generatedAt: now,
      updatedAt: now,
    };
    const currentGenerationId = parsed.data.currentGeneration?.id;
    let generationId = "";

    if (currentGenerationId && ObjectId.isValid(currentGenerationId)) {
      const updated = await db.collection("generations").findOneAndUpdate(
        { _id: new ObjectId(currentGenerationId), userId: creditReservation.userId },
        { $set: generationRecord },
        { returnDocument: "after", projection: { _id: 1 } },
      );

      generationId = updated.value?._id.toString() ?? "";
    }

    if (!generationId) {
      const saved = await db.collection("generations").insertOne({
        ...generationRecord,
        createdAt: now,
      });
      generationId = saved.insertedId.toString();
    }

    return NextResponse.json({
      generation: result,
      generationId,
      filesChanged: getFileChanges(result.files, parsed.data.currentGeneration?.files ?? []),
      creditsRemaining: creditReservation.credits,
      creditLimit: FREE_SIGNUP_CREDITS,
    });
  } catch (error) {
    await refundGenerationCredit(users, creditReservation.userId);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : "Generation failed. Please try again." },
      { status: 500 },
    );
  }
}

function getFileChanges(nextFiles: z.infer<typeof generationSchema>["files"], previousFiles: Array<{ path: string; content: string }>) {
  const previousByPath = new Map(previousFiles.map((file) => [file.path, file.content]));

  return nextFiles
    .map((file) => {
      const previousContent = previousByPath.get(file.path);

      if (previousContent === undefined) {
        return { path: file.path, action: "created" as const };
      }

      if (previousContent !== file.content) {
        return { path: file.path, action: "edited" as const };
      }

      return null;
    })
    .filter((fileChange): fileChange is z.infer<typeof fileChangeSchema> => Boolean(fileChange));
}

function enforceGenerationQuality(prompt: string, generation: z.infer<typeof generationSchema>) {
  const qualityIssues = validateGeneratedQuality(prompt, generation);

  if (qualityIssues.length) {
    console.warn(`[Mosaic generation] generated UI quality warnings: ${qualityIssues.join("; ")}`);
  }

  return generation;
}

function validateGeneratedQuality(prompt: string, generation: z.infer<typeof generationSchema>) {
  const content = `${generation.previewHtml} ${generation.previewCss} ${generation.files.map((file) => file.content).join(" ")}`.toLowerCase();
  const issues: string[] = [];
  const sectionCount = (content.match(/<section|section class|function [a-z0-9]+section|const [a-z0-9]+section/gi) ?? []).length;
  const cardSignals = (content.match(/card|article|grid|thumbnail|product|metric|testimonial/g) ?? []).length;
  const repeatedItemSignals = (content.match(/article|post|tweet|video|product|row|metric|testimonial|card|item/g) ?? []).length;
  const hasResponsiveClasses = /\b(sm|md|lg|xl|2xl):/.test(content) || /@media\s*\(/.test(content);
  const hasStyledButton = /button|rounded-full|hover:|transition/.test(content);
  const hasNavigation = /<nav|navitems|navbar|sidebar|topbar|header/.test(content);
  const hasPlaceholderOnlyText = /video title|lorem ipsum|placeholder|card title|product name/i.test(content);
  const isComplexPrompt = /clone|dashboard|analytics|social|video|youtube|twitter|facebook|ecommerce|store|shop|marketplace|app/i.test(prompt);

  if (sectionCount < 4 && !/clone|dashboard|app interface/i.test(prompt)) issues.push("too few meaningful sections");
  if (isComplexPrompt && cardSignals < 10) issues.push("too few repeated cards/items");
  if (isComplexPrompt && repeatedItemSignals < 12) issues.push("too little realistic repeated content");
  if (!hasResponsiveClasses) issues.push("missing responsive Tailwind/media classes");
  if (!hasStyledButton) issues.push("buttons or interactions are under-styled");
  if (!hasNavigation) issues.push("navigation is missing or weak");
  if (hasPlaceholderOnlyText) issues.push("placeholder-only copy detected");
  if (generation.previewHtml.length < 4500 || generation.previewCss.length < 2200) issues.push("preview is too small/basic");

  return issues;
}

function createReliableGeneration(prompt: string, reason: string): z.infer<typeof generationSchema> {
  const analysis = analyzePrompt(prompt);
  const title = getFallbackTitle(prompt, analysis.websiteType);
  const theme = getFallbackTheme(analysis.websiteType);
  const sections = getReliableSections(prompt, analysis.websiteType);
  const previewHtml = renderReliablePreview({ title, prompt, sections, theme, websiteType: analysis.websiteType });
  const previewCss = renderReliableCss(theme);
  const appFile = renderReliableApp({ title, prompt, sections, theme, websiteType: analysis.websiteType });

  return {
    title,
    summary: `A polished ${analysis.websiteType.replace(/-/g, " ")} generated for: ${prompt}.`,
    previewHtml,
    previewCss,
    previewJs: "",
    files: createReliableFiles(appFile, title),
    notes: [`Used reliable local generation because ${reason}.`],
  };
}

type ReliableSection = {
  eyebrow: string;
  title: string;
  description: string;
  items: Array<{ title: string; meta: string; description: string }>;
};

type ReliableTheme = {
  background: string;
  surface: string;
  surfaceAlt: string;
  text: string;
  muted: string;
  accent: string;
  accentSoft: string;
  border: string;
};

function getFallbackTitle(prompt: string, websiteType: WebsiteType) {
  const clean = prompt
    .replace(/\b(build|make|create|design|generate|please|a|an|the|website|site|app|page|clone|for|me)\b/gi, " ")
    .replace(/\s+/g, " ")
    .trim();

  if (/youtube|video/i.test(prompt)) return "YouTube";
  if (/twitter|x clone|tweet/i.test(prompt)) return "Pulse";
  if (/facebook/i.test(prompt)) return "Connect";
  if (/ecommerce|shop|store|product/i.test(prompt)) return "Nova Store";
  if (/dashboard|analytics|admin/i.test(prompt)) return "Mosaic Analytics";
  if (/cafe|coffee|restaurant/i.test(prompt)) return "Lumen Cafe";
  if (/portfolio/i.test(prompt)) return "Studio Portfolio";

  return clean ? toTitleCase(clean).slice(0, 42) : toTitleCase(websiteType.replace(/-/g, " "));
}

function getFallbackTheme(websiteType: WebsiteType): ReliableTheme {
  if (websiteType === "fashion-ecommerce" || websiteType === "restaurant-cafe") {
    return {
      background: "#f8f3ec",
      surface: "rgba(255,255,255,.72)",
      surfaceAlt: "#1f1712",
      text: "#211a16",
      muted: "#77685d",
      accent: "#a15c38",
      accentSoft: "rgba(161,92,56,.14)",
      border: "rgba(33,26,22,.12)",
    };
  }

  return {
    background: "#09090b",
    surface: "rgba(255,255,255,.075)",
    surfaceAlt: "rgba(255,255,255,.11)",
    text: "#f8fafc",
    muted: "#a1a1aa",
    accent: "#38bdf8",
    accentSoft: "rgba(56,189,248,.14)",
    border: "rgba(255,255,255,.12)",
  };
}

function getReliableSections(prompt: string, websiteType: WebsiteType): ReliableSection[] {
  if (websiteType === "social-feed") {
    return [
      {
        eyebrow: "Live timeline",
        title: "A social feed that feels active from the first screen",
        description: "Post composer, trending topics, creator suggestions, and a dense responsive timeline.",
        items: [
          { title: "Ava Patel", meta: "@ava_builds · 4m · 12K views", description: "Shipping a cleaner creator dashboard today. The best products make complicated workflows feel calm." },
          { title: "Mosaic Studio", meta: "@mosaic · 12m · 8.4K views", description: "New release: faster previews, richer generated layouts, and smarter responsive behavior." },
          { title: "Ryan Chen", meta: "@ryanchendesign · 31m · 19K views", description: "Tiny details that make a feed feel real: hover states, timestamps, soft dividers, and good empty states." },
          { title: "Nora Labs", meta: "@noralabs · 1h · 24K views", description: "We rebuilt onboarding around one question: what does the user need to do next?" },
        ],
      },
      {
        eyebrow: "Trending now",
        title: "Topics people are talking about",
        description: "Relevant trends, follow suggestions, and engagement metrics fill the side panel.",
        items: [
          { title: "#BuildInPublic", meta: "18.2K posts", description: "Founders sharing launches, metrics, and product notes." },
          { title: "AI design systems", meta: "7,920 posts", description: "Teams comparing prompts, components, and generation quality." },
          { title: "Frontend Friday", meta: "4,108 posts", description: "New interfaces, UI experiments, and code snippets." },
        ],
      },
    ];
  }

  if (websiteType === "video-platform-dashboard") {
    return [
      {
        eyebrow: "Watch next",
        title: "A dense video home feed with search, chips, and creator metadata",
        description: "A YouTube-style browsing interface with a sidebar, sticky controls, and responsive video cards.",
        items: [
          { title: "Building a cinematic desk setup", meta: "Studio Desk · 1.2M views · 3 days ago", description: "12:48" },
          { title: "React workflow I use every day", meta: "Frontend Lab · 486K views · 1 week ago", description: "24:10" },
          { title: "AI tools that actually save time", meta: "Ops Weekly · 137K views · 2 days ago", description: "15:09" },
          { title: "Designing thumbnails that people click", meta: "Northline Films · 604K views · 4 days ago", description: "9:41" },
          { title: "Live coding a SaaS dashboard", meta: "Code Room · 318K views · 2 days ago", description: "31:08" },
          { title: "Creator economy tools nobody mentions", meta: "Signal Media · 92K views · 18 hours ago", description: "18:32" },
        ],
      },
    ];
  }

  if (websiteType === "admin-dashboard") {
    return [
      {
        eyebrow: "Overview",
        title: "Metrics, charts, activity, and customer data in one view",
        description: "A polished operational dashboard with real stats and dense data sections.",
        items: [
          { title: "$128.4K", meta: "Revenue · +18.2%", description: "Monthly recurring revenue across paid workspaces." },
          { title: "24,892", meta: "Active users · +9.7%", description: "Teams who opened projects this week." },
          { title: "97.8%", meta: "Uptime · stable", description: "Preview generation availability over the last 30 days." },
          { title: "1,284", meta: "New projects", description: "Fresh generations created this month." },
        ],
      },
      {
        eyebrow: "Recent activity",
        title: "Latest workspace events",
        description: "Generated projects, upgraded accounts, and project exports.",
        items: [
          { title: "Acme Studio", meta: "Generated ecommerce storefront", description: "2 minutes ago" },
          { title: "Northstar", meta: "Exported React project ZIP", description: "18 minutes ago" },
          { title: "Orbit Labs", meta: "Updated dashboard color system", description: "41 minutes ago" },
        ],
      },
    ];
  }

  if (websiteType === "fashion-ecommerce" || /shop|store|ecommerce|product/i.test(prompt)) {
    return [
      {
        eyebrow: "Featured collection",
        title: "Products made for modern living",
        description: "A premium storefront with category chips, product cards, trust cues, testimonials, and FAQ.",
        items: [
          { title: "Linen Utility Jacket", meta: "$148 · 4.9 rating", description: "Structured midweight layer with soft brushed lining." },
          { title: "Everyday Travel Tote", meta: "$96 · Bestseller", description: "Roomy carryall with laptop sleeve and magnetic closure." },
          { title: "Cloud Knit Set", meta: "$128 · New", description: "Relaxed two-piece set with a refined lounge silhouette." },
          { title: "Ceramic Desk Lamp", meta: "$74 · Limited", description: "Warm diffused lighting for workspaces and bedrooms." },
        ],
      },
      {
        eyebrow: "Why customers return",
        title: "A store experience built around trust",
        description: "Fast shipping, easy returns, curated bundles, and polished merchandising.",
        items: [
          { title: "Free 3-day shipping", meta: "Orders over $75", description: "Tracked delivery with proactive updates." },
          { title: "30-day returns", meta: "No stress", description: "Simple exchanges and instant return labels." },
          { title: "Curated edits", meta: "Weekly drops", description: "Fresh collections with clear product storytelling." },
        ],
      },
    ];
  }

  return [
    {
      eyebrow: "Launch-ready",
      title: `A polished first version for ${prompt}`,
      description: "Responsive sections, realistic content, strong hierarchy, and a complete visual system.",
      items: [
        { title: "Premium hero", meta: "Clear CTA and proof", description: "A first screen with strong messaging, supporting copy, and visual depth." },
        { title: "Feature grid", meta: "Useful details", description: "Cards with specific benefits, icons, hover states, and real microcopy." },
        { title: "Workflow section", meta: "Step-by-step", description: "Explains how the product works with polished layout rhythm." },
        { title: "Pricing and FAQ", meta: "Conversion ready", description: "Practical plan cards, objections, and footer navigation." },
      ],
    },
    {
      eyebrow: "Built for every screen",
      title: "Responsive from mobile to desktop",
      description: "The layout stacks cleanly, keeps readable type, and preserves strong spacing.",
      items: [
        { title: "Mobile nav", meta: "Compact", description: "Navigation collapses into clean, thumb-friendly actions." },
        { title: "Balanced grids", meta: "Adaptive", description: "Cards move from single column to multi-column layouts." },
        { title: "Readable copy", meta: "Accessible", description: "Contrast, line length, and hierarchy stay comfortable." },
      ],
    },
  ];
}

function renderReliablePreview({
  title,
  prompt,
  sections,
  theme,
  websiteType,
}: {
  title: string;
  prompt: string;
  sections: ReliableSection[];
  theme: ReliableTheme;
  websiteType: WebsiteType;
}) {
  const navItems = websiteType === "social-feed" ? ["Home", "Explore", "Messages", "Profile"] : ["Overview", "Features", "Showcase", "FAQ"];
  const hero = sections[0];

  return `<main class="reliable-site ${websiteType}">
  <nav class="reliable-nav">
    <strong>${escapeHtml(title)}</strong>
    <div>${navItems.map((item) => `<a href="#">${escapeHtml(item)}</a>`).join("")}</div>
    <button>${websiteType.includes("dashboard") || websiteType.includes("social") ? "Open app" : "Get started"}</button>
  </nav>
  <section class="reliable-hero">
    <div>
      <p class="eyebrow">${escapeHtml(hero.eyebrow)}</p>
      <h1>${escapeHtml(hero.title)}</h1>
      <span>${escapeHtml(hero.description)}</span>
      <div class="hero-actions"><button>Start building</button><button class="secondary">View demo</button></div>
    </div>
    <aside class="preview-panel">
      ${hero.items
        .slice(0, 4)
        .map(
          (item, index) => `<article>
        <i>${String(index + 1).padStart(2, "0")}</i>
        <div><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.meta)}</p><small>${escapeHtml(item.description)}</small></div>
      </article>`,
        )
        .join("")}
    </aside>
  </section>
  ${sections
    .map(
      (section) => `<section class="reliable-section">
    <div class="section-head"><p class="eyebrow">${escapeHtml(section.eyebrow)}</p><h2>${escapeHtml(section.title)}</h2><span>${escapeHtml(section.description)}</span></div>
    <div class="reliable-grid">${section.items
      .map(
        (item) => `<article class="reliable-card">
      <span>${escapeHtml(item.meta)}</span>
      <h3>${escapeHtml(item.title)}</h3>
      <p>${escapeHtml(item.description)}</p>
    </article>`,
      )
      .join("")}</div>
  </section>`,
    )
    .join("")}
  <footer><strong>${escapeHtml(title)}</strong><span>Generated from: ${escapeHtml(prompt)}</span></footer>
</main>`;
}

function renderReliableCss(theme: ReliableTheme) {
  return `*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:${theme.background};color:${theme.text};font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}button,a{font:inherit}.reliable-site{min-height:100vh;background:radial-gradient(circle at 12% 0%,${theme.accentSoft},transparent 28rem),${theme.background};padding:24px;color:${theme.text}}.reliable-nav,.reliable-hero,.reliable-section,footer{max-width:1180px;margin-left:auto;margin-right:auto}.reliable-nav{display:flex;align-items:center;justify-content:space-between;gap:18px;border:1px solid ${theme.border};border-radius:999px;background:${theme.surface};padding:14px 16px 14px 22px;backdrop-filter:blur(18px);box-shadow:0 24px 80px rgba(0,0,0,.16)}.reliable-nav strong{font-size:24px;letter-spacing:-.045em}.reliable-nav div{display:flex;gap:6px;flex-wrap:wrap}.reliable-nav a{border-radius:999px;color:${theme.muted};padding:9px 12px;text-decoration:none}.reliable-nav a:hover{background:${theme.accentSoft};color:${theme.text}}button{border:0;border-radius:999px;background:${theme.text};color:${theme.background};cursor:pointer;font-weight:850;padding:12px 17px;transition:transform .2s,opacity .2s}button:hover{opacity:.9;transform:translateY(-1px)}.secondary{border:1px solid ${theme.border};background:transparent;color:${theme.text}}.reliable-hero{display:grid;grid-template-columns:1.05fr .95fr;gap:22px;align-items:stretch;padding:52px 0 24px}.reliable-hero>div,.preview-panel,.reliable-card,.section-head{border:1px solid ${theme.border};background:${theme.surface};box-shadow:0 30px 100px rgba(0,0,0,.16)}.reliable-hero>div{align-content:center;border-radius:36px;padding:52px}.eyebrow{color:${theme.accent};font-size:12px;font-weight:900;letter-spacing:.18em;margin:0;text-transform:uppercase}.reliable-hero h1{font-size:clamp(46px,7vw,82px);font-weight:720;letter-spacing:-.065em;line-height:.9;margin:18px 0}.reliable-hero span,.section-head span,.reliable-card p,.preview-panel small,footer span{color:${theme.muted};line-height:1.72}.reliable-hero span{display:block;font-size:18px;max-width:690px}.hero-actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:30px}.preview-panel{display:grid;align-content:end;gap:12px;border-radius:36px;min-height:520px;padding:22px;background:linear-gradient(145deg,${theme.surface},${theme.accentSoft})}.preview-panel article{display:grid;grid-template-columns:44px 1fr;gap:12px;border:1px solid ${theme.border};border-radius:22px;background:${theme.surface};padding:15px}.preview-panel i{display:grid;place-items:center;width:38px;height:38px;border-radius:999px;background:${theme.accentSoft};color:${theme.accent};font-style:normal;font-weight:900}.preview-panel h3,.reliable-card h3{margin:0;color:${theme.text};letter-spacing:-.025em}.preview-panel p{margin:4px 0;color:${theme.accent};font-size:13px;font-weight:800}.reliable-section{padding:16px 0}.section-head{border-radius:30px;margin-bottom:14px;padding:28px}.section-head h2{font-size:clamp(30px,4vw,52px);letter-spacing:-.055em;line-height:1;margin:12px 0}.reliable-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.reliable-card{border-radius:26px;padding:22px;min-height:190px}.reliable-card span{color:${theme.accent};font-size:12px;font-weight:900;text-transform:uppercase}.reliable-card h3{font-size:22px;margin:18px 0 10px}footer{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:34px 0;color:${theme.muted}}@media(max-width:980px){.reliable-hero{grid-template-columns:1fr}.preview-panel{min-height:auto}.reliable-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:680px){.reliable-site{padding:14px}.reliable-nav,footer{align-items:flex-start;flex-direction:column;border-radius:26px}.reliable-hero{padding:18px 0}.reliable-hero>div{padding:30px}.reliable-hero h1{font-size:42px}.reliable-grid{grid-template-columns:1fr}.preview-panel article{grid-template-columns:1fr}}`;
}

function renderReliableApp({
  title,
  prompt,
  sections,
  theme,
  websiteType,
}: {
  title: string;
  prompt: string;
  sections: ReliableSection[];
  theme: ReliableTheme;
  websiteType: WebsiteType;
}) {
  return `const sections = ${JSON.stringify(sections, null, 2)};
const navItems = ${JSON.stringify(websiteType === "social-feed" ? ["Home", "Explore", "Messages", "Profile"] : ["Overview", "Features", "Showcase", "FAQ"])};

export default function App() {
  const hero = sections[0];

  return (
    <main className="min-h-screen bg-[${theme.background}] px-4 py-4 text-[${theme.text}] sm:px-6">
      <nav className="mx-auto flex max-w-6xl flex-col gap-4 rounded-[28px] border border-white/10 bg-white/[0.07] px-5 py-4 shadow-2xl shadow-black/10 backdrop-blur md:flex-row md:items-center md:justify-between">
        <strong className="text-2xl tracking-[-0.045em]">${escapeJsx(title)}</strong>
        <div className="flex flex-wrap gap-2">{navItems.map((item) => <a className="rounded-full px-3 py-2 text-sm text-zinc-400 transition hover:bg-white/10 hover:text-white" href="#" key={item}>{item}</a>)}</div>
        <button className="rounded-full bg-white px-4 py-3 text-sm font-bold text-zinc-950">Get started</button>
      </nav>

      <section className="mx-auto grid max-w-6xl gap-6 py-10 lg:grid-cols-[1.05fr_.95fr]">
        <div className="rounded-[36px] border border-white/10 bg-white/[0.07] p-8 shadow-2xl shadow-black/10 md:p-12">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-sky-300">{hero.eyebrow}</p>
          <h1 className="mt-5 max-w-3xl text-5xl font-bold leading-[0.9] tracking-[-0.065em] md:text-7xl">{hero.title}</h1>
          <p className="mt-6 max-w-2xl text-lg leading-8 text-zinc-400">{hero.description}</p>
          <div className="mt-8 flex flex-wrap gap-3">
            <button className="rounded-full bg-white px-5 py-3 font-bold text-zinc-950">Start building</button>
            <button className="rounded-full border border-white/10 px-5 py-3 font-bold text-white">View demo</button>
          </div>
        </div>
        <aside className="grid content-end gap-3 rounded-[36px] border border-white/10 bg-gradient-to-br from-white/[0.08] to-sky-400/10 p-5 shadow-2xl shadow-black/10">
          {hero.items.slice(0, 4).map((item, index) => (
            <article className="grid grid-cols-[44px_1fr] gap-3 rounded-3xl border border-white/10 bg-white/[0.07] p-4" key={item.title}>
              <i className="grid h-10 w-10 place-items-center rounded-full bg-sky-400/10 text-sm font-black not-italic text-sky-300">{String(index + 1).padStart(2, "0")}</i>
              <div>
                <h3 className="font-semibold tracking-[-0.02em]">{item.title}</h3>
                <p className="mt-1 text-sm font-bold text-sky-300">{item.meta}</p>
                <small className="mt-2 block leading-6 text-zinc-400">{item.description}</small>
              </div>
            </article>
          ))}
        </aside>
      </section>

      {sections.map((section) => (
        <section className="mx-auto max-w-6xl py-3" key={section.title}>
          <div className="mb-4 rounded-[30px] border border-white/10 bg-white/[0.07] p-7">
            <p className="text-xs font-black uppercase tracking-[0.2em] text-sky-300">{section.eyebrow}</p>
            <h2 className="mt-3 text-4xl font-bold tracking-[-0.055em] md:text-5xl">{section.title}</h2>
            <p className="mt-3 max-w-3xl leading-7 text-zinc-400">{section.description}</p>
          </div>
          <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
            {section.items.map((item) => (
              <article className="min-h-48 rounded-[26px] border border-white/10 bg-white/[0.07] p-6 shadow-xl shadow-black/10 transition hover:-translate-y-1 hover:bg-white/[0.1]" key={item.title}>
                <span className="text-xs font-black uppercase text-sky-300">{item.meta}</span>
                <h3 className="mt-4 text-xl font-semibold tracking-[-0.025em]">{item.title}</h3>
                <p className="mt-3 leading-7 text-zinc-400">{item.description}</p>
              </article>
            ))}
          </div>
        </section>
      ))}

      <footer className="mx-auto flex max-w-6xl flex-col gap-2 py-8 text-zinc-500 md:flex-row md:items-center md:justify-between">
        <strong>${escapeJsx(title)}</strong>
        <span>Generated from: ${escapeJsx(prompt)}</span>
      </footer>
    </main>
  );
}
`;
}

function createReliableFiles(appFile: string, title: string): z.infer<typeof generationSchema>["files"] {
  return [
    {
      path: "package.json",
      content: JSON.stringify(
        {
          scripts: { dev: "vite", build: "vite build", preview: "vite preview" },
          dependencies: { "@vitejs/plugin-react": "^4.3.1", autoprefixer: "^10.4.20", postcss: "^8.4.49", react: "^18.2.0", "react-dom": "^18.2.0", tailwindcss: "^3.4.17", vite: "^5.4.0" },
          devDependencies: {},
        },
        null,
        2,
      ),
    },
    { path: "index.html", content: `<title>${escapeHtml(title)}</title><div id="root"></div><script type="module" src="/src/main.jsx"></script>\n` },
    { path: "src/main.jsx", content: "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport './index.css';\nimport App from './App.jsx';\n\ncreateRoot(document.getElementById('root')).render(<App />);\n" },
    { path: "src/App.jsx", content: appFile },
    { path: "src/index.css", content: "@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\nbody { margin: 0; }\n" },
    { path: "tailwind.config.js", content: "export default { content: ['./index.html', './src/**/*.{js,jsx}'], theme: { extend: {} }, plugins: [] };\n" },
    { path: "postcss.config.js", content: "export default { plugins: { tailwindcss: {}, autoprefixer: {} } };\n" },
    { path: "README.md", content: `# ${title}\n\nGenerated by Mosaic.\n` },
  ];
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeJsx(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function toTitleCase(value: string) {
  return value.replace(/\w\S*/g, (word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase()).replace(/\s+/g, " ").trim();
}

async function improveGenerationQuality({
  provider,
  apiKey,
  originalPrompt,
  issues,
  generation,
}: {
  provider: AiProvider;
  apiKey: string;
  originalPrompt: string;
  issues: string[];
  generation: z.infer<typeof generationSchema>;
}) {
  return generateWithAi({
    provider,
    apiKey,
    prompt: [
      originalPrompt,
      "",
      "The UI is too basic. Improve it into a polished production-quality interface with richer layout, better spacing, realistic content, responsive sections, modern visual design, and complete components.",
      `Quality issues to fix: ${issues.join("; ")}`,
      "Return the full updated project JSON with complete files and self-contained preview fields.",
    ].join("\n"),
    currentGeneration: {
      title: generation.title,
      summary: generation.summary,
      prompt: originalPrompt,
      previewHtml: generation.previewHtml,
      previewCss: generation.previewCss,
      previewJs: generation.previewJs,
      files: generation.files,
    },
  });
}

async function generateWithAi(input: {
  provider: AiProvider;
  apiKey: string;
  figmaLink?: string;
  prompt: string;
  referenceImage?: { data: string; mimeType: string; name: string };
  currentGeneration?: z.infer<typeof requestSchema>["currentGeneration"];
}) {
  if (input.provider === "openrouter") {
    return generateWithOpenRouter(input);
  }

  return generateWithGemini(input);
}

async function generateWithOpenRouter({
  apiKey,
  figmaLink,
  prompt,
  referenceImage,
  currentGeneration,
}: {
  apiKey: string;
  figmaLink?: string;
  prompt: string;
  referenceImage?: { data: string; mimeType: string; name: string };
  currentGeneration?: z.infer<typeof requestSchema>["currentGeneration"];
}) {
  const baseUrl = (process.env.OPENROUTER_BASE_URL?.trim() || "https://openrouter.ai/api/v1").replace(/\/+$/, "");
  const model = process.env.OPENROUTER_MODEL?.trim() || "openrouter/free";
  const promptText = extractGeminiPromptText(createGeminiPayload({ figmaLink, prompt, referenceImage, currentGeneration }));
  const errors: string[] = [];

  for (let attempt = 1; attempt <= maxAiAttemptsPerModel; attempt += 1) {
    let response: Response;

    try {
      response = await fetchWithTimeout(`${baseUrl}/chat/completions`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${apiKey}`,
          "Content-Type": "application/json",
          "HTTP-Referer": process.env.NEXT_PUBLIC_APP_URL ?? "http://localhost:3000",
          "X-Title": "Mosaic",
        },
        body: JSON.stringify({
          model,
          temperature: 0.5,
          top_p: 0.9,
          max_tokens: Number(process.env.OPENROUTER_MAX_TOKENS ?? 16000),
          response_format: { type: "json_object" },
          messages: [
            {
              role: "system",
              content: `${WEBSITE_GENERATION_SYSTEM_PROMPT}\n\n${PREMIUM_OUTPUT_REQUIREMENTS}\n\nReturn only valid JSON. No markdown. No explanations.`,
            },
            {
              role: "user",
              content: referenceImage
                ? [
                    { type: "text", text: promptText },
                    {
                      type: "image_url",
                      image_url: {
                        url: `data:${referenceImage.mimeType};base64,${referenceImage.data}`,
                      },
                    },
                  ]
                : promptText,
            },
          ],
        }),
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "OpenRouter request timed out";
      errors.push(`${model}: ${message}`);

      if (attempt < maxAiAttemptsPerModel) {
        await wait(900 * attempt);
        continue;
      }

      break;
    }

    const data = (await response.json().catch(() => null)) as OpenRouterResponse | null;

    if (!response.ok) {
      const message = data?.error?.message ?? `OpenRouter returned ${response.status}`;
      errors.push(`${model}: ${message}`);

      if (attempt < maxAiAttemptsPerModel && isTemporaryAiError(response.status, message)) {
        await wait(900 * attempt);
        continue;
      }

      break;
    }

    const content = data?.choices?.[0]?.message?.content;
    const text = Array.isArray(content) ? content.map((part) => part.text ?? "").join("\n").trim() : content?.trim();

    if (!text) {
      errors.push(`${model}: returned an empty response`);
      break;
    }

    return parseGeneration(text);
  }

  if (errors.some((error) => isTemporaryAiError(undefined, error))) {
    throw new Error("OpenRouter is temporarily unavailable. Please run it again in a minute.");
  }

  throw new Error(errors[0] ?? "OpenRouter did not return a usable generation.");
}

async function generateWithGemini({
  apiKey,
  figmaLink,
  prompt,
  referenceImage,
  currentGeneration,
}: {
  apiKey: string;
  figmaLink?: string;
  prompt: string;
  referenceImage?: { data: string; mimeType: string; name: string };
  currentGeneration?: z.infer<typeof requestSchema>["currentGeneration"];
}) {
  const preferredModel = process.env.GEMINI_MODEL?.trim();
  const models = Array.from(new Set([preferredModel, ...geminiFallbackModels].filter(Boolean))) as string[];
  const payload = createGeminiPayload({ figmaLink, prompt, referenceImage, currentGeneration });
  const errors: string[] = [];

  for (const model of models) {
    for (let attempt = 1; attempt <= maxAiAttemptsPerModel; attempt += 1) {
      let response: Response;

      try {
        response = await fetchWithTimeout(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`, {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-goog-api-key": apiKey,
          },
          body: JSON.stringify(payload),
        });
      } catch (error) {
        const message = error instanceof Error ? error.message : `${model} request timed out`;
        errors.push(`${model}: ${message}`);

        if (attempt < maxAiAttemptsPerModel) {
          await wait(900 * attempt);
          continue;
        }

        break;
      }

      const data = (await response.json().catch(() => null)) as GeminiResponse | null;

      if (!response.ok) {
        const message = data?.error?.message ?? `${model} returned ${response.status}`;
        errors.push(`${model}: ${message}`);

        if (attempt < maxAiAttemptsPerModel && isTemporaryAiError(response.status, message)) {
          await wait(900 * attempt);
          continue;
        }

        break;
      }

      const text = data?.candidates?.[0]?.content?.parts?.map((part) => part.text ?? "").join("\n").trim();

      if (!text) {
        errors.push(`${model}: returned an empty response`);
        break;
      }

      return parseGeneration(text);
    }
  }

  if (errors.some((error) => isTemporaryAiError(undefined, error))) {
    throw new Error("Gemini is temporarily overloaded. I tried the available fallback models, but they are busy right now. Please run it again in a minute.");
  }

  throw new Error(errors[0] ?? "Gemini did not return a usable generation.");
}

function createGeminiPayload({
  figmaLink,
  prompt,
  referenceImage,
  currentGeneration,
}: {
  figmaLink?: string;
  prompt: string;
  referenceImage?: { data: string; mimeType: string; name: string };
  currentGeneration?: z.infer<typeof requestSchema>["currentGeneration"];
}) {
  const cloneGuidance = getCloneGuidance(prompt);
  const promptAnalysis = analyzePrompt(prompt);
  const enhancedBrief = enhanceUserPrompt(prompt);
  const currentProjectContext = currentGeneration
    ? [
        "",
        "Existing project context for a follow-up edit:",
        `Current id: ${currentGeneration.id ?? "none"}`,
        `Current title: ${currentGeneration.title ?? "Untitled"}`,
        `Original/previous prompt: ${currentGeneration.prompt ?? "none"}`,
        `Current summary: ${currentGeneration.summary ?? "none"}`,
        "When existing project context is provided, treat the user prompt as an edit request. Preserve the existing app concept, pages, layout, content, interactions, responsiveness, and file structure unless the user explicitly asks to replace them.",
        "Return the FULL updated project JSON, not a patch. Include every required file with complete updated contents.",
        "Current previewHtml:",
        truncateForPrompt(currentGeneration.previewHtml ?? "", 9000),
        "Current previewCss:",
        truncateForPrompt(currentGeneration.previewCss ?? "", 9000),
        currentGeneration.previewJs ? `Current previewJs:\n${truncateForPrompt(currentGeneration.previewJs, 4500)}` : "Current previewJs: none",
        "Current files:",
        serializeFilesForPrompt(currentGeneration.files ?? []),
      ].join("\n")
    : "";

  return {
    generationConfig: {
      temperature: 0.5,
      topP: 0.9,
      maxOutputTokens: Number(process.env.GEMINI_MAX_OUTPUT_TOKENS ?? 16000),
      responseMimeType: "application/json",
    },
    contents: [
      {
        role: "user",
        parts: [
          {
            text: [
              WEBSITE_GENERATION_SYSTEM_PROMPT,
              PREMIUM_OUTPUT_REQUIREMENTS,
              "Return ONLY valid JSON with this shape:",
              '{"title":"string","summary":"string","previewHtml":"string","previewCss":"string","previewJs":"string","files":[{"path":"string","content":"string"}],"notes":["string"]}',
              "First infer the product type, target audience, and primary user action. Then build a complete, realistic React + Tailwind website, app screen, dashboard, landing page, or mini-flow based on the user request.",
              "Respect the user's requested product identity. Do not rebrand requested products as Mosaic, MosaicTube, MonoAI, or any other house brand unless the user explicitly asks for that.",
              "If the user asks for a clone, remake the recognizable product pattern as closely as possible within React/Tailwind: layout, navigation, spacing, colors, page density, content types, and core interactions should match the referenced product.",
              "For well-known product clone requests, keep the requested product name in visible UI copy when the user uses that name. Example: a YouTube clone should look like YouTube, say YouTube where appropriate, use video feed/sidebar/top search/player patterns, and should not become MosaicTube.",
              "Do not make a shallow or tiny mockup. For clone requests, include enough visible real estate and realistic repeated content to feel like the actual app: sidebars, top bars, cards/lists, filters/tabs, empty/loading states, and responsive mobile behavior.",
              "For social/feed clone requests, build the actual product shell: desktop sidebar, main composer/feed, right trends/suggestions column, mobile bottom nav, many realistic posts, handles, avatars, timestamps, replies, reposts, likes, and interaction buttons.",
              "For video platform clone requests, include a sticky topbar, search, sidebar, category chips, at least 12 realistic video cards, thumbnail art made with CSS gradients, channel avatars, durations, views, and upload times.",
              "For dashboards, include at least 4 metric cards, a CSS chart, activity feed, filters, and a populated table with realistic rows.",
              "For ecommerce, include at least 8 products, category chips, product cards with prices, badges, ratings, cart actions, trust cues, testimonials, FAQ, and footer.",
              "For landing/marketing pages, include at least 6 meaningful sections: navbar, hero, proof/stat strip, feature grid, workflow/product preview, pricing or use cases, testimonials/FAQ, and footer.",
              "For ecommerce/fashion prompts, create a premium brand experience with a clean navbar, luxury hero, product grid, category cards, collection section, editorial lookbook, brand story, testimonials, newsletter signup, and footer.",
              "The files array must represent a proper Vite React project folder structure.",
              "Always include at least these files: package.json, index.html, src/main.jsx, src/App.jsx, src/index.css, tailwind.config.js, postcss.config.js, README.md.",
              "If the app naturally has multiple pages or major views, implement real in-app navigation in src/App.jsx using route state or hash navigation, and include matching links in previewHtml with href values like /, #pricing, #settings, or #dashboard.",
              "The previewHtml navigation links must correspond to visible sections or views so an external page selector can activate them.",
              "Use package.json dependencies compatible with a standard Vite React Tailwind project: react, react-dom, @vitejs/plugin-react, vite, tailwindcss 3.x, postcss, and autoprefixer.",
              "Use React and Tailwind CSS only. Use Tailwind utility classes throughout the React components. Keep custom CSS minimal and only for base styles, keyframes, or small animations.",
              "Design quality is as important as functionality. Prioritize spacing, typography, hierarchy, alignment, visual balance, and responsive polish.",
              "Mobile-first responsive design is required. Every layout must work on mobile, tablet, and desktop.",
              "Use max-w-7xl or equivalent max-width containers for major sections. Use generous whitespace, balanced sections, intelligent grids, and consistent alignment.",
              "Prefer large typography and strong hierarchy: text-4xl through text-7xl for major headings when appropriate, with readable body copy and clear secondary text.",
              "Prefer p-6, p-8, p-10, p-12; gap-6, gap-8, gap-10; rounded-xl, rounded-2xl, rounded-3xl; subtle borders; shadow-md/shadow-lg; and restrained premium gradients.",
              "Avoid cramped p-2 layouts, tiny text, default-looking buttons, generic boxy cards, outdated styling, excessive text density, and beginner tutorial aesthetics.",
              "Use modern card-based UI patterns where useful. Every section should feel intentionally designed rather than templated.",
              "Add hover states, focus states, transitions, micro-interactions, loading/empty states where appropriate, and accessibility considerations such as semantic elements, aria labels, visible focus, and sufficient contrast.",
              "Use realistic mock content and domain-specific details instead of lorem ipsum.",
              "Write reusable React components with clean names and minimal duplication. Separate major sections into components when appropriate.",
              "Do not use remote images, iframes, backend calls, or paid libraries. Use local gradients, SVG, CSS, and realistic placeholder data.",
              "Never output broken image placeholders. If a thumbnail, avatar, logo, or media image is needed, create it with CSS gradients, inline SVG, emoji-free lettermarks, or data-safe markup instead of <img src> values that may fail.",
              "previewHtml/previewCss/previewJs must be a self-contained static preview of the generated app for an iframe. It should visually match the React output.",
              "CRITICAL PREVIEW RULES: previewHtml must contain visible body markup, not an empty #root element, not JSX, and not a full HTML document. Do not include html/head/body/style/script tags in previewHtml.",
              "CRITICAL PREVIEW QUALITY: previewHtml should usually be at least 4500 characters and previewCss at least 2500 characters unless the user explicitly asks for something tiny. A shorter response is usually too basic.",
              "previewCss must be ordinary browser CSS without @tailwind directives or style tags. previewJs must be plain browser JavaScript without imports, exports, JSX, TypeScript, or script tags.",
              "The preview may use Tailwind utility classes because the preview iframe loads Tailwind CDN, but include enough visible markup that it renders immediately without React.",
              "The generated React code should be clean, componentized when useful, accessible, responsive, and ready to run with npm install && npm run dev.",
              "Before returning JSON, self-review spacing, typography hierarchy, responsiveness, visual polish, accessibility, and whether any section feels generic. Upgrade weak sections until the result feels production-ready for paying customers.",
              "If the UI is too basic, improve it before responding: richer layout, better spacing, realistic content, responsive sections, modern visual design, and complete components.",
              "For follow-up edit requests like changing font size, colors, spacing, copy, sections, responsiveness, or component behavior, update the existing project directly and keep everything else stable.",
              cloneGuidance,
              "Avoid markdown fences. Avoid explanations outside JSON.",
              currentProjectContext,
              "",
              `User prompt: ${prompt}`,
              `Prompt analysis: ${JSON.stringify(promptAnalysis)}`,
              `Enhanced build brief: ${enhancedBrief}`,
              figmaLink ? `Figma/reference link: ${figmaLink}` : "Figma/reference link: none provided",
              referenceImage
                ? `Reference image attached: ${referenceImage.name}. Use it as visual guidance for layout, spacing, typography, colors, and cloning the design when requested.`
                : "Reference image attached: none",
            ].join("\n"),
          },
          ...(referenceImage
            ? [
                {
                  inline_data: {
                    data: referenceImage.data,
                    mime_type: referenceImage.mimeType,
                  },
                },
              ]
            : []),
        ],
      },
    ],
  };
}

function extractGeminiPromptText(payload: ReturnType<typeof createGeminiPayload>) {
  const part = payload.contents[0]?.parts[0];
  return part && "text" in part ? part.text : "";
}

function analyzePrompt(prompt: string): PromptAnalysis {
  const normalizedPrompt = prompt.toLowerCase();
  const brandName = extractBrandName(prompt);
  const cloneIntent = getCloneIntent(prompt);
  const websiteType = getWebsiteTypeFromPrompt(normalizedPrompt, cloneIntent);
  const visualStyle = getVisualStyleFromPrompt(normalizedPrompt, websiteType);
  const requiredSections = getRequiredSectionsForType(websiteType);
  const targetAudience = getTargetAudienceForType(websiteType);

  return { websiteType, visualStyle, requiredSections, brandName, targetAudience, cloneIntent };
}

function getDesignInspiration(analysis: PromptAnalysis) {
  if (process.env.DESIGN_SEARCH_ENABLED?.toLowerCase() !== "true" || !process.env.DESIGN_SEARCH_API_KEY) {
    return "";
  }

  const query = `${analysis.visualStyle.join(" ")} ${analysis.websiteType.replace(/-/g, " ")} website design inspiration`;
  return `Optional design search is configured. Use inspiration query "${query}" only for high-level layout and visual direction; do not copy code or proprietary template assets.`;
}

function buildEnhancedDesignBrief(prompt: string, analysis: PromptAnalysis, inspiration: string) {
  return [
    `Build a polished ${analysis.websiteType.replace(/-/g, " ")} for this request: ${prompt}.`,
    analysis.brandName ? `Use the brand name "${analysis.brandName}" prominently and consistently.` : "Create a fitting brand name only if the user did not provide one.",
    analysis.cloneIntent ? `Clone intent: create a polished ${analysis.cloneIntent}-inspired interface without copying protected assets or external code.` : "",
    `Target audience: ${analysis.targetAudience}.`,
    `Visual style: ${analysis.visualStyle.join(", ")}.`,
    `Suggested sections/components: ${analysis.requiredSections.join(", ")}.`,
    inspiration,
    "If this is an app, dashboard, marketplace, or clone request, render the actual application interface instead of a marketing landing page.",
    "Make the result feel populated and usable on first load: realistic data, multiple states, clear navigation, and enough repeated items to judge the product.",
    "Generate a fresh full React + Tailwind implementation and a matching self-contained preview. Do not output a wireframe. Do not output placeholder-only cards. Use populated data arrays and reusable components where useful.",
  ]
    .filter(Boolean)
    .join("\n");
}

function enhanceUserPrompt(prompt: string) {
  const analysis = analyzePrompt(prompt);
  const inspiration = getDesignInspiration(analysis);
  const buildBrief = buildEnhancedDesignBrief(prompt, analysis, inspiration);
  const normalizedPrompt = prompt.toLowerCase();
  const brandName = analysis.brandName;

  if (/yt|youtube/.test(normalizedPrompt) && /clone|app|platform|dashboard/.test(normalizedPrompt)) {
    return `${buildBrief}\nBuild a polished YouTube-inspired video platform dashboard with a sticky top navbar, left sidebar navigation, search bar, category chips, responsive video grid, realistic thumbnail cards, duration badges, channel avatars, video titles, creators, views, upload time, hover states, dark premium surfaces, dense desktop layout, and mobile layout.`;
  }

  if (isFashionBrandPrompt(prompt)) {
    return `${buildBrief}\nBuild a premium modern fashion ecommerce landing page for a clothing brand${brandName ? ` called ${brandName}` : ""} with an elegant navbar, luxury hero section, collection highlights, product cards, category tiles, editorial lookbook, brand story, testimonials, newsletter signup, and footer. Use refined typography, soft gradients, high-quality spacing, responsive grids, polished Tailwind styling, realistic product copy, and a premium brand atmosphere.`;
  }

  if (/shop|store|ecommerce|e-commerce|product|cart|checkout/.test(normalizedPrompt)) {
    return `${buildBrief}\nBuild a premium ecommerce storefront with a polished navbar, hero, category chips, product grid, featured collection, trust badges, testimonials, newsletter, and footer. Use realistic products, prices, merchandising copy, responsive layouts, hover states, and modern Tailwind styling.`;
  }

  if (/dashboard|analytics|admin|crm|chart|metrics/.test(normalizedPrompt)) {
    return `${buildBrief}\nBuild a production-quality SaaS dashboard with sidebar navigation, topbar, metric cards, fake charts built with CSS, activity feed, customer table, filters, responsive layout, hover states, and realistic operating data.`;
  }

  if (/portfolio|personal|resume|designer|developer|creator/.test(normalizedPrompt)) {
    return `${buildBrief}\nBuild a polished portfolio website with a strong hero, selected work grid, services/process section, case-study cards, testimonials, contact CTA, footer, responsive layout, and refined editorial typography.`;
  }

  if (prompt.trim().split(/\s+/).length <= 8) {
    return `${buildBrief}\nBuild a polished, production-quality responsive website for: ${prompt}. Include a premium hero, clear navigation, complete sections, realistic content, strong visual hierarchy, responsive grids, styled buttons, hover states, subtle gradients, cards with depth, and a footer.`;
  }

  return buildBrief;
}

function extractBrandName(prompt: string) {
  const match = prompt.match(/\b(?:called|named|brand\s+called|brand\s+named)\s+["']?([a-zA-Z0-9][a-zA-Z0-9\s-]{1,32})["']?/i);

  if (!match?.[1]) {
    return "";
  }

  return match[1]
    .replace(/\b(?:with|for|that|website|site|landing|page|store|shop|brand|clothing|fashion)\b.*$/i, "")
    .trim();
}

function getCloneIntent(prompt: string) {
  const normalizedPrompt = prompt.toLowerCase();

  if (/youtube|yt\b/.test(normalizedPrompt)) return "YouTube";
  if (/twitter|x clone|tweet/.test(normalizedPrompt)) return "Twitter/X";
  if (/airbnb|booking marketplace|rental/.test(normalizedPrompt)) return "Airbnb";
  if (/facebook|instagram|tiktok|social/.test(normalizedPrompt)) return "social network";

  return /clone|replica|copy|same as/.test(normalizedPrompt) ? "product clone" : "";
}

function getWebsiteTypeFromPrompt(prompt: string, cloneIntent: string): WebsiteType {
  if (/youtube|yt\b|video|streaming|channel|shorts/.test(prompt)) return "video-platform-dashboard";
  if (/twitter|x clone|tweet|social|feed|facebook|instagram|tiktok/.test(prompt)) return "social-feed";
  if (/airbnb|marketplace|booking|rental|travel stay|property/.test(prompt)) return "marketplace";
  if (/clothing|fashion|apparel|streetwear|boutique|wear|garment|collection/.test(prompt)) return "fashion-ecommerce";
  if (/cafe|coffee|restaurant|bistro|bakery|brunch|diner|food|menu/.test(prompt)) return "restaurant-cafe";
  if (/dashboard|admin|analytics|crm|metrics|chart|table/.test(prompt)) return "admin-dashboard";
  if (/portfolio|resume|personal|designer|developer|creator|photographer/.test(prompt)) return "portfolio";
  if (/agency|studio|creative|service business/.test(prompt)) return "agency";
  if (/fintech|finance|bank|payment|wallet|invest/.test(prompt)) return "fintech-landing";
  if (/mobile app|ios|android|app landing/.test(prompt)) return "mobile-app-landing";
  if (/ai|chatbot|automation|agent/.test(prompt)) return "ai-tool-landing";
  if (cloneIntent) return "generic";
  return "saas-landing";
}

function isFashionBrandPrompt(prompt: string) {
  return /clothing|fashion|apparel|streetwear|boutique|wear|garment|collection/i.test(prompt);
}

function getVisualStyleFromPrompt(prompt: string, websiteType: WebsiteType) {
  const styles = new Set<string>();

  if (/dark|black|neon|cyber/.test(prompt)) styles.add("dark");
  if (/luxury|premium|elegant|minimal/.test(prompt)) styles.add("luxury");
  if (/playful|fun|colorful/.test(prompt)) styles.add("playful");
  if (/futuristic|ai|glass/.test(prompt)) styles.add("futuristic");
  if (/editorial|magazine|fashion/.test(prompt)) styles.add("editorial");

  const defaults: Record<WebsiteType, string[]> = {
    "saas-landing": ["startup", "premium", "minimal"],
    "ai-tool-landing": ["futuristic", "glassmorphism", "premium"],
    "fashion-ecommerce": ["luxury", "minimal", "editorial"],
    "restaurant-cafe": ["warm", "editorial", "hospitality"],
    portfolio: ["editorial", "minimal", "personal"],
    agency: ["bold", "creative", "premium"],
    "video-platform-dashboard": ["modern", "dashboard", "media"],
    "social-feed": ["dark", "social", "dense"],
    marketplace: ["clean", "marketplace"],
    "fintech-landing": ["trustworthy", "premium", "data"],
    "mobile-app-landing": ["consumer", "polished", "playful"],
    "admin-dashboard": ["operational", "dense", "dark"],
    generic: ["premium", "responsive"],
  };

  defaults[websiteType].forEach((style) => styles.add(style));
  return [...styles].slice(0, 5);
}

function getRequiredSectionsForType(websiteType: WebsiteType) {
  const sections: Record<WebsiteType, string[]> = {
    "saas-landing": ["navbar", "hero", "features", "workflow", "pricing", "faq", "footer"],
    "ai-tool-landing": ["navbar", "hero", "prompt-console", "capabilities", "workflow", "use-cases", "footer"],
    "fashion-ecommerce": ["navbar", "hero", "collections", "product-grid", "lookbook", "testimonials", "footer"],
    "restaurant-cafe": ["navbar", "hero", "hours", "menu", "story", "visit", "footer"],
    portfolio: ["navbar", "hero", "selected-work", "services", "process", "contact", "footer"],
    agency: ["navbar", "hero", "services", "case-studies", "process", "contact", "footer"],
    "video-platform-dashboard": ["topbar", "sidebar", "category-tabs", "video-grid", "video-card", "shorts-row"],
    "social-feed": ["sidebar", "timeline", "composer", "trends", "who-to-follow", "mobile-tabs"],
    marketplace: ["navbar", "search", "filters", "listing-grid", "detail-cards", "footer"],
    "fintech-landing": ["navbar", "hero", "stats", "product-preview", "security", "features", "footer"],
    "mobile-app-landing": ["navbar", "hero", "phone-mockup", "features", "reviews", "download-cta", "footer"],
    "admin-dashboard": ["sidebar", "topbar", "metrics", "chart", "activity", "table", "filters"],
    generic: ["navbar", "hero", "content", "features", "footer"],
  };

  return sections[websiteType];
}

function getTargetAudienceForType(websiteType: WebsiteType) {
  const audiences: Record<WebsiteType, string> = {
    "saas-landing": "startup buyers and product teams",
    "ai-tool-landing": "teams evaluating AI workflow tools",
    "fashion-ecommerce": "style-conscious shoppers and fashion brand visitors",
    "restaurant-cafe": "local guests, brunch customers, and coffee regulars",
    portfolio: "clients, recruiters, and collaborators",
    agency: "brands looking for creative or technical services",
    "video-platform-dashboard": "video viewers and creators",
    "social-feed": "community members and content creators",
    marketplace: "buyers browsing listings and hosts/sellers",
    "fintech-landing": "customers comparing trusted financial products",
    "mobile-app-landing": "mobile-first consumers",
    "admin-dashboard": "operators, analysts, and internal teams",
    generic: "website visitors",
  };

  return audiences[websiteType];
}

function parseGeneration(text: string) {
  const cleaned = text
    .trim()
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```$/i, "");

  const jsonStart = cleaned.indexOf("{");
  const jsonEnd = cleaned.lastIndexOf("}");
  const jsonText = jsonStart >= 0 && jsonEnd > jsonStart ? cleaned.slice(jsonStart, jsonEnd + 1) : cleaned;
  const parsed = generationSchema.safeParse(JSON.parse(jsonText));

  if (!parsed.success) {
    throw new Error("AI provider returned code in an unexpected format. Please try again.");
  }

  return parsed.data;
}

function getCloneGuidance(prompt: string) {
  const normalizedPrompt = prompt.toLowerCase();

  if (!normalizedPrompt.includes("clone")) {
    return "";
  }

  if (normalizedPrompt.includes("youtube")) {
    return [
      "Specific YouTube clone requirements:",
      "- Build a faithful YouTube-style UI, not a renamed alternative brand.",
      "- Visible brand should be YouTube unless the user asks for a different name.",
      "- Include a sticky top bar with menu, YouTube wordmark area, centered search, voice/action icons, and user avatar.",
      "- Include a left navigation rail/sidebar with Home, Shorts, Subscriptions, Library/History-style items.",
      "- Include category chips, a dense responsive video grid, thumbnail blocks, durations, channel avatars, titles, channel names, views, and upload age.",
      "- Use dark or light YouTube-like surfaces intentionally, with strong contrast and no broken image icons.",
      "- On mobile, collapse the sidebar and keep the feed/search experience usable.",
    ].join("\n");
  }

  if (normalizedPrompt.includes("twitter") || /\bx clone\b/.test(normalizedPrompt) || normalizedPrompt.includes("tweet")) {
    return [
      "Specific Twitter/X clone requirements:",
      "- Build a recognizable Twitter/X-style social dashboard, not a generic landing page.",
      "- Use a three-column desktop layout: left navigation, center timeline, right trends/who-to-follow panel.",
      "- Include a composer with avatar, audience controls, media/action buttons, and a primary post button.",
      "- Include at least 8 realistic posts with names, handles, timestamps, post text, optional media-like cards, reply/repost/like/view counts, and hover states.",
      "- Include trending topics, who-to-follow suggestions, sticky navigation behavior, and mobile bottom tabs.",
      "- Use dense but readable spacing, dark or light social app surfaces, clear separators, and realistic microcopy.",
    ].join("\n");
  }

  if (normalizedPrompt.includes("facebook")) {
    return [
      "Specific Facebook clone requirements:",
      "- Build a recognizable Facebook-style social home feed, not a generic landing page.",
      "- Include a top navigation bar with search, tabs, action buttons, and profile controls.",
      "- Include a left shortcuts/sidebar column, central story row/composer/feed, and right contacts/sponsored/trending column on desktop.",
      "- Include at least 8 realistic posts, reactions, comments, share actions, story cards, group/page suggestions, and responsive mobile stacking.",
    ].join("\n");
  }

  return "Clone request requirement: preserve the recognizable identity and interaction pattern of the requested product instead of inventing a generic renamed version.";
}

function serializeFilesForPrompt(files: Array<{ path: string; content: string }>) {
  const importantFiles = files
    .filter((file) =>
      [
        "package.json",
        "index.html",
        "src/main.jsx",
        "src/App.jsx",
        "src/index.css",
        "tailwind.config.js",
        "postcss.config.js",
        "README.md",
      ].includes(file.path),
    )
    .slice(0, 10);

  if (importantFiles.length === 0) {
    return "No files available.";
  }

  return importantFiles
    .map((file) => `--- ${file.path} ---\n${truncateForPrompt(file.content, 12000)}`)
    .join("\n\n");
}

function truncateForPrompt(value: string, maxLength: number) {
  if (value.length <= maxLength) {
    return value;
  }

  return `${value.slice(0, maxLength)}\n...[truncated]`;
}

function getAiProvider(): AiProvider {
  return process.env.AI_PROVIDER?.trim().toLowerCase() === "openrouter" ? "openrouter" : "gemini";
}

function isTemporaryAiError(status: number | undefined, message: string) {
  const lowerMessage = message.toLowerCase();
  return (
    status === 429 ||
    status === 500 ||
    status === 502 ||
    status === 503 ||
    status === 504 ||
    lowerMessage.includes("high demand") ||
    lowerMessage.includes("overloaded") ||
    lowerMessage.includes("rate limit") ||
    lowerMessage.includes("quota") ||
    lowerMessage.includes("temporarily") ||
    lowerMessage.includes("try again later") ||
    lowerMessage.includes("unavailable")
  );
}

async function fetchWithTimeout(url: string, init: RequestInit) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), aiRequestTimeoutMs);

  try {
    return await fetch(url, { ...init, signal: controller.signal });
  } finally {
    clearTimeout(timeout);
  }
}

function wait(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
